[package]
name = "pikuma"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.9.3"
glam = "0.24.2"
rlua = "0.19.7"
imgui-rs = "*"
